import sampleWithReplacement from "./sample";

const topicOptions = [
  { value: "forex", label: "Currency" },
  { value: "holiday", label: "Holidays" },
  { value: "anything", label: "Anything" },
];

// A long scroll...
const countries = [
  {
    currency: "AFN",
    currencyName: "Afghan afghani",
    country: "Afghanistan",
    isoAlpha2: "AF",
    isoNumeric3: "004",
  },
  {
    currency: "ALL",
    currencyName: "Albanian lek",
    country: "Albania",
    isoAlpha2: "AL",
    isoNumeric3: "008",
  },
  {
    currency: "DZD",
    currencyName: "Algerian dinar",
    country: "Algeria",
    isoAlpha2: "DZ",
    isoNumeric3: "012",
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Andorra",
    isoAlpha2: "AD",
    isoNumeric3: "020",
  },
  {
    currency: "AOA",
    currencyName: "Angolan kwanza",
    country: "Angola",
    isoAlpha2: "AO",
    isoNumeric3: "024",
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean dollar",
    country: "Antigua and Barbuda",
    isoAlpha2: "AG",
    isoNumeric3: "028",
  },
  {
    currency: "ARS",
    currencyName: "Argentine peso",
    country: "Argentina",
    isoAlpha2: "AR",
    isoNumeric3: "032",
  },
  {
    currency: "AMD",
    currencyName: "Armenian dram",
    country: "Armenia",
    isoAlpha2: "AM",
    isoNumeric3: "051",
  },
  {
    currency: "AUD",
    currencyName: "Australian dollar",
    country: "Australia",
    isoAlpha2: "AU",
    isoNumeric3: "036",
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Austria",
    isoAlpha2: "AT",
    isoNumeric3: "040",
  },
  {
    currency: "AZN",
    currencyName: "Azerbaijani manat",
    country: "Azerbaijan",
    isoAlpha2: "AZ",
    isoNumeric3: "031",
  },
  {
    currency: "BSD",
    currencyName: "Bahamian dollar",
    country: "Bahamas",
    isoAlpha2: "BS",
    isoNumeric3: "044",
  },
  {
    currency: "BHD",
    currencyName: "Bahraini dinar",
    country: "Bahrain",
    isoAlpha2: "BH",
    isoNumeric3: "048",
  },
  {
    currency: "BDT",
    currencyName: "Bangladeshi taka",
    country: "Bangladesh",
    isoAlpha2: "BD",
    isoNumeric3: "050",
  },
  {
    currency: "BBD",
    currencyName: "Barbadian dollar",
    country: "Barbados",
    isoAlpha2: "BB",
    isoNumeric3: "052",
  },
  {
    currency: "BYR",
    currencyName: "Belarusian ruble",
    country: "Belarus",
    isoAlpha2: "BY",
    isoNumeric3: 112,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Belgium",
    isoAlpha2: "BE",
    isoNumeric3: "056",
  },
  {
    currency: "BZD",
    currencyName: "Belize dollar",
    country: "Belize",
    isoAlpha2: "BZ",
    isoNumeric3: "084",
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Benin",
    isoAlpha2: "BJ",
    isoNumeric3: 204,
  },
  {
    currency: "BTN",
    currencyName: "Bhutanese ngultrum",
    country: "Bhutan",
    isoAlpha2: "BT",
    isoNumeric3: "064",
  },
  {
    currency: "BOB",
    currencyName: "Bolivian boliviano",
    country: "Bolivia",
    isoAlpha2: "BO",
    isoNumeric3: "068",
  },
  {
    currency: "BAM",
    currencyName: "Bosnia and Herzegovina convertible mark",
    country: "Bosnia and Herzegovina",
    isoAlpha2: "BA",
    isoNumeric3: "070",
  },
  {
    currency: "BWP",
    currencyName: "Botswana pula",
    country: "Botswana",
    isoAlpha2: "BW",
    isoNumeric3: "072",
  },
  {
    currency: "BRL",
    currencyName: "Brazilian real",
    country: "Brazil",
    isoAlpha2: "BR",
    isoNumeric3: "076",
  },
  {
    currency: "BND",
    currencyName: "Brunei dollar",
    country: "Brunei",
    isoAlpha2: "BN",
    isoNumeric3: "096",
  },
  {
    currency: "BGN",
    currencyName: "Bulgarian lev",
    country: "Bulgaria",
    isoAlpha2: "BG",
    isoNumeric3: 100,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Burkina Faso",
    isoAlpha2: "BF",
    isoNumeric3: 854,
  },
  {
    currency: "BIF",
    currencyName: "Burundian franc",
    country: "Burundi",
    isoAlpha2: "BI",
    isoNumeric3: 108,
  },
  {
    currency: "KHR",
    currencyName: "Cambodian riel",
    country: "Cambodia",
    isoAlpha2: "KH",
    isoNumeric3: 116,
  },
  {
    currency: "XAF",
    currencyName: "Central African CFA franc",
    country: "Cameroon",
    isoAlpha2: "CM",
    isoNumeric3: 120,
  },
  {
    currency: "CAD",
    currencyName: "Canadian dollar",
    country: "Canada",
    isoAlpha2: "CA",
    isoNumeric3: 124,
  },
  {
    currency: "CVE",
    currencyName: "Cape Verdean escudo",
    country: "Cape Verde",
    isoAlpha2: "CV",
    isoNumeric3: 132,
  },
  {
    currency: "XAF",
    currencyName: "Central African CFA franc",
    country: "Central African Republic",
    isoAlpha2: "CF",
    isoNumeric3: 140,
  },
  {
    currency: "XAF",
    currencyName: "Central African CFA franc",
    country: "Chad",
    isoAlpha2: "TD",
    isoNumeric3: 148,
  },
  {
    currency: "CLP",
    currencyName: "Chilean peso",
    country: "Chile",
    isoAlpha2: "CL",
    isoNumeric3: 152,
  },
  {
    currency: "CNY",
    currencyName: "Chinese yuan",
    country: "China",
    isoAlpha2: "CN",
    isoNumeric3: 156,
  },
  {
    currency: "COP",
    currencyName: "Colombian peso",
    country: "Colombia",
    isoAlpha2: "CO",
    isoNumeric3: 170,
  },
  {
    currency: "KMF",
    currencyName: "Comorian franc",
    country: "Comoros",
    isoAlpha2: "KM",
    isoNumeric3: 174,
  },
  {
    currency: "XAF",
    currencyName: "Central African CFA franc",
    country: "Congo",
    isoAlpha2: "KM",
    isoNumeric3: 178,
  },
  {
    currency: "CRC",
    currencyName: "Costa Rican colón",
    country: "Costa Rica",
    isoAlpha2: "CR",
    isoNumeric3: 188,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Côte d'Ivoire",
    isoAlpha2: "CR",
    isoNumeric3: 384,
  },
  {
    currency: "HRK",
    currencyName: "Croatian kuna",
    country: "Croatia",
    isoAlpha2: "HR",
    isoNumeric3: 191,
  },
  {
    currency: "CUP",
    currencyName: "Cuban peso",
    country: "Cuba",
    isoAlpha2: "CU",
    isoNumeric3: 192,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Cyprus",
    isoAlpha2: "CY",
    isoNumeric3: 196,
  },
  {
    currency: "CZK",
    currencyName: "Czech koruna",
    country: "Czechia",
    isoAlpha2: "CZ",
    isoNumeric3: 203,
  },
  {
    currency: "CDF",
    currencyName: "Congolese franc",
    country: "Democratic Republic of the Congo",
    isoAlpha2: "CD",
    isoNumeric3: 180,
  },
  {
    currency: "DKK",
    currencyName: "Danish krone",
    country: "Denmark",
    isoAlpha2: "DK",
    isoNumeric3: 208,
  },
  {
    currency: "DJF",
    currencyName: "Djiboutian franc",
    country: "Djibouti",
    isoAlpha2: "DJ",
    isoNumeric3: 262,
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean dollar",
    country: "Dominica",
    isoAlpha2: "DM",
    isoNumeric3: 212,
  },
  {
    currency: "DOP",
    currencyName: "Dominican peso",
    country: "Dominican Republic",
    isoAlpha2: "DO",
    isoNumeric3: 214,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "Ecuador",
    isoAlpha2: "EC",
    isoNumeric3: 218,
  },
  {
    currency: "EGP",
    currencyName: "Egyptian pound",
    country: "Egypt",
    isoAlpha2: "EG",
    isoNumeric3: 818,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "El Salvador",
    isoAlpha2: "SV",
    isoNumeric3: 222,
  },
  {
    currency: "XAF",
    currencyName: "Central African CFA franc",
    country: "Equatorial Guinea",
    isoAlpha2: "GQ",
    isoNumeric3: 226,
  },
  {
    currency: "ERN",
    currencyName: "Eritrean nakfa",
    country: "Eritrea",
    isoAlpha2: "ER",
    isoNumeric3: 232,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Estonia",
    isoAlpha2: "EE",
    isoNumeric3: 233,
  },
  {
    currency: "SZL",
    currencyName: "Swazi lilangeni",
    country: "Eswatini",
    isoAlpha2: "EE",
    isoNumeric3: 748,
  },
  {
    currency: "ETB",
    currencyName: "Ethiopian birr",
    country: "Ethiopia",
    isoAlpha2: "ET",
    isoNumeric3: 231,
  },
  {
    currency: "FJD",
    currencyName: "Fijian dollar",
    country: "Fiji",
    isoAlpha2: "FJ",
    isoNumeric3: 242,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Finland",
    isoAlpha2: "FI",
    isoNumeric3: 246,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "France",
    isoAlpha2: "FR",
    isoNumeric3: 250,
  },
  {
    currency: "XAF",
    currencyName: "Central African CFA franc",
    country: "Gabon",
    isoAlpha2: "GA",
    isoNumeric3: 266,
  },
  {
    currency: "GMD",
    currencyName: "Gambian dalasi",
    country: "Gambia",
    isoAlpha2: "GM",
    isoNumeric3: 270,
  },
  {
    currency: "GEL",
    currencyName: "Georgian lari",
    country: "Georgia",
    isoAlpha2: "GE",
    isoNumeric3: 268,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Germany",
    isoAlpha2: "DE",
    isoNumeric3: 276,
  },
  {
    currency: "GHS",
    currencyName: "Ghanaian cedi",
    country: "Ghana",
    isoAlpha2: "GH",
    isoNumeric3: 288,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Greece",
    isoAlpha2: "GR",
    isoNumeric3: 300,
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean dollar",
    country: "Grenada",
    isoAlpha2: "GD",
    isoNumeric3: 308,
  },
  {
    currency: "GTQ",
    currencyName: "Guatemalan quetzal",
    country: "Guatemala",
    isoAlpha2: "GT",
    isoNumeric3: 320,
  },
  {
    currency: "GNF",
    currencyName: "Guinean franc",
    country: "Guinea",
    isoAlpha2: "GN",
    isoNumeric3: 324,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Guinea-Bissau",
    isoAlpha2: "GW",
    isoNumeric3: 624,
  },
  {
    currency: "GYD",
    currencyName: "Guyanese dollar",
    country: "Guyana",
    isoAlpha2: "GY",
    isoNumeric3: 328,
  },
  {
    currency: "HTG",
    currencyName: "Haitian gourde",
    country: "Haiti",
    isoAlpha2: "HT",
    isoNumeric3: 332,
  },
  {
    currency: "HNL",
    currencyName: "Honduran lempira",
    country: "Honduras",
    isoAlpha2: "HN",
    isoNumeric3: 340,
  },
  {
    currency: "HUF",
    currencyName: "Hungarian forint",
    country: "Hungary",
    isoAlpha2: "HU",
    isoNumeric3: 348,
  },
  {
    currency: "ISK",
    currencyName: "Icelandic króna",
    country: "Iceland",
    isoAlpha2: "IS",
    isoNumeric3: 352,
  },
  {
    currency: "INR",
    currencyName: "Indian rupee",
    country: "India",
    isoAlpha2: "IN",
    isoNumeric3: 356,
  },
  {
    currency: "IDR",
    currencyName: "Indonesian rupiah",
    country: "Indonesia",
    isoAlpha2: "ID",
    isoNumeric3: 360,
  },
  {
    currency: "IRR",
    currencyName: "Iranian rial",
    country: "Iran",
    isoAlpha2: "IR",
    isoNumeric3: 364,
  },
  {
    currency: "IQD",
    currencyName: "Iraqi dinar",
    country: "Iraq",
    isoAlpha2: "IQ",
    isoNumeric3: 368,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Ireland",
    isoAlpha2: "IE",
    isoNumeric3: 372,
  },
  {
    currency: "ILS",
    currencyName: "Israeli new shekel",
    country: "Israel",
    isoAlpha2: "IL",
    isoNumeric3: 376,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Italy",
    isoAlpha2: "IT",
    isoNumeric3: 380,
  },
  {
    currency: "JMD",
    currencyName: "Jamaican dollar",
    country: "Jamaica",
    isoAlpha2: "JM",
    isoNumeric3: 388,
  },
  {
    currency: "JPY",
    currencyName: "Japanese yen",
    country: "Japan",
    isoAlpha2: "JP",
    isoNumeric3: 392,
  },
  {
    currency: "JOD",
    currencyName: "Jordanian dinar",
    country: "Jordan",
    isoAlpha2: "JO",
    isoNumeric3: 400,
  },
  {
    currency: "KZT",
    currencyName: "Kazakhstani tenge",
    country: "Kazakhstan",
    isoAlpha2: "KZ",
    isoNumeric3: 398,
  },
  {
    currency: "KES",
    currencyName: "Kenyan shilling",
    country: "Kenya",
    isoAlpha2: "KE",
    isoNumeric3: 404,
  },
  {
    currency: "AUD",
    currencyName: "Australian dollar",
    country: "Kiribati",
    isoAlpha2: "KI",
    isoNumeric3: 296,
  },
  {
    currency: "KWD",
    currencyName: "Kuwaiti dinar",
    country: "Kuwait",
    isoAlpha2: "KW",
    isoNumeric3: 414,
  },
  {
    currency: "KGS",
    currencyName: "Kyrgyzstani som",
    country: "Kyrgyzstan",
    isoAlpha2: "KG",
    isoNumeric3: 417,
  },
  {
    currency: "LAK",
    currencyName: "Lao kip",
    country: "Laos",
    isoAlpha2: "LA",
    isoNumeric3: 418,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Latvia",
    isoAlpha2: "LV",
    isoNumeric3: 428,
  },
  {
    currency: "LBP",
    currencyName: "Lebanese pound",
    country: "Lebanon",
    isoAlpha2: "LB",
    isoNumeric3: 422,
  },
  {
    currency: "LSL",
    currencyName: "Lesotho loti",
    country: "Lesotho",
    isoAlpha2: "LS",
    isoNumeric3: 426,
  },
  {
    currency: "LRD",
    currencyName: "Liberian dollar",
    country: "Liberia",
    isoAlpha2: "LR",
    isoNumeric3: 430,
  },
  {
    currency: "LYD",
    currencyName: "Libyan dinar",
    country: "Libya",
    isoAlpha2: "LY",
    isoNumeric3: 434,
  },
  {
    currency: "CHF",
    currencyName: "Swiss franc",
    country: "Liechtenstein",
    isoAlpha2: "LI",
    isoNumeric3: 438,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Lithuania",
    isoAlpha2: "LT",
    isoNumeric3: 440,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Luxembourg",
    isoAlpha2: "LU",
    isoNumeric3: 442,
  },
  {
    currency: "MGA",
    currencyName: "Malagasy ariary",
    country: "Madagascar",
    isoAlpha2: "MG",
    isoNumeric3: 450,
  },
  {
    currency: "MWK",
    currencyName: "Malawian kwacha",
    country: "Malawi",
    isoAlpha2: "MW",
    isoNumeric3: 454,
  },
  {
    currency: "MYR",
    currencyName: "Malaysian ringgit",
    country: "Malaysia",
    isoAlpha2: "MY",
    isoNumeric3: 458,
  },
  {
    currency: "MVR",
    currencyName: "Maldivian rufiyaa",
    country: "Maldives",
    isoAlpha2: "MV",
    isoNumeric3: 462,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Mali",
    isoAlpha2: "ML",
    isoNumeric3: 466,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Malta",
    isoAlpha2: "MT",
    isoNumeric3: 470,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "Marshall Islands",
    isoAlpha2: "MH",
    isoNumeric3: 584,
  },
  {
    currency: "MRO",
    currencyName: "Mauritanian ouguiya",
    country: "Mauritania",
    isoAlpha2: "MR",
    isoNumeric3: 478,
  },
  {
    currency: "MUR",
    currencyName: "Mauritian rupee",
    country: "Mauritius",
    isoAlpha2: "MU",
    isoNumeric3: 480,
  },
  {
    currency: "MXN",
    currencyName: "Mexican peso",
    country: "Mexico",
    isoAlpha2: "MX",
    isoNumeric3: 484,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "Micronesia",
    isoAlpha2: "FM",
    isoNumeric3: 583,
  },
  {
    currency: "MDL",
    currencyName: "Moldovan leu",
    country: "Moldova",
    isoAlpha2: "MD",
    isoNumeric3: 498,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Monaco",
    isoAlpha2: "MC",
    isoNumeric3: 492,
  },
  {
    currency: "MNT",
    currencyName: "Mongolian tögrög",
    country: "Mongolia",
    isoAlpha2: "MN",
    isoNumeric3: 496,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Montenegro",
    isoAlpha2: "ME",
    isoNumeric3: 499,
  },
  {
    currency: "MAD",
    currencyName: "Moroccan dirham",
    country: "Morocco",
    isoAlpha2: "MA",
    isoNumeric3: 504,
  },
  {
    currency: "MZN",
    currencyName: "Mozambican metical",
    country: "Mozambique",
    isoAlpha2: "MZ",
    isoNumeric3: 508,
  },
  {
    currency: "MMK",
    currencyName: "Burmese kyat",
    country: "Myanmar",
    isoAlpha2: "MM",
    isoNumeric3: 104,
  },
  {
    currency: "NAD",
    currencyName: "Namibian dollar",
    country: "Namibia",
    isoAlpha2: "NA",
    isoNumeric3: 516,
  },
  {
    currency: "AUD",
    currencyName: "Australian dollar",
    country: "Nauru",
    isoAlpha2: "NR",
    isoNumeric3: 520,
  },
  {
    currency: "NPR",
    currencyName: "Nepalese rupee",
    country: "Nepal",
    isoAlpha2: "NP",
    isoNumeric3: 524,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Netherlands",
    isoAlpha2: "NL",
    isoNumeric3: 528,
  },
  {
    currency: "NZD",
    currencyName: "New Zealand dollar",
    country: "New Zealand",
    isoAlpha2: "NZ",
    isoNumeric3: 554,
  },
  {
    currency: "NIO",
    currencyName: "Nicaraguan córdoba",
    country: "Nicaragua",
    isoAlpha2: "NI",
    isoNumeric3: 558,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Niger",
    isoAlpha2: "NE",
    isoNumeric3: 562,
  },
  {
    currency: "NGN",
    currencyName: "Nigerian naira",
    country: "Nigeria",
    isoAlpha2: "NG",
    isoNumeric3: 566,
  },
  {
    currency: "KPW",
    currencyName: "North Korean won",
    country: "North Korea",
    isoAlpha2: "NG",
    isoNumeric3: 408,
  },
  {
    currency: "MKD",
    currencyName: "Macedonian denar",
    country: "North Macedonia",
    isoAlpha2: "NG",
    isoNumeric3: 807,
  },
  {
    currency: "NOK",
    currencyName: "Norwegian krone",
    country: "Norway",
    isoAlpha2: "NO",
    isoNumeric3: 578,
  },
  {
    currency: "OMR",
    currencyName: "Omani rial",
    country: "Oman",
    isoAlpha2: "OM",
    isoNumeric3: 512,
  },
  {
    currency: "PKR",
    currencyName: "Pakistani rupee",
    country: "Pakistan",
    isoAlpha2: "PK",
    isoNumeric3: 586,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "Palau",
    isoAlpha2: "PW",
    isoNumeric3: 585,
  },
  {
    currency: "ILS",
    currencyName: "Israeli new shekel",
    country: "Palestine",
    isoAlpha2: "PS",
    isoNumeric3: 275,
  },
  {
    currency: "PAB",
    currencyName: "Panamanian balboa",
    country: "Panama",
    isoAlpha2: "PA",
    isoNumeric3: 591,
  },
  {
    currency: "PGK",
    currencyName: "Papua New Guinean kina",
    country: "Papua New Guinea",
    isoAlpha2: "PG",
    isoNumeric3: 598,
  },
  {
    currency: "PYG",
    currencyName: "Paraguayan guaraní",
    country: "Paraguay",
    isoAlpha2: "PY",
    isoNumeric3: 600,
  },
  {
    currency: "PEN",
    currencyName: "Peruvian sol",
    country: "Peru",
    isoAlpha2: "PE",
    isoNumeric3: 604,
  },
  {
    currency: "PHP",
    currencyName: "Philippine peso",
    country: "Philippines",
    isoAlpha2: "PH",
    isoNumeric3: 608,
  },
  {
    currency: "PLN",
    currencyName: "Polish zloty",
    country: "Poland",
    isoAlpha2: "PL",
    isoNumeric3: 616,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Portugal",
    isoAlpha2: "PT",
    isoNumeric3: 620,
  },
  {
    currency: "QAR",
    currencyName: "Qatari riyal",
    country: "Qatar",
    isoAlpha2: "QA",
    isoNumeric3: 634,
  },
  {
    currency: "RON",
    currencyName: "Romanian leu",
    country: "Romania",
    isoAlpha2: "RO",
    isoNumeric3: 642,
  },
  {
    currency: "RUB",
    currencyName: "Russian ruble",
    country: "Russia",
    isoAlpha2: "RU",
    isoNumeric3: 643,
  },
  {
    currency: "RWF",
    currencyName: "Rwandan franc",
    country: "Rwanda",
    isoAlpha2: "RW",
    isoNumeric3: 646,
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean dollar",
    country: "Saint Kitts and Nevis",
    isoAlpha2: "KN",
    isoNumeric3: 659,
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean dollar",
    country: "Saint Lucia",
    isoAlpha2: "LC",
    isoNumeric3: 662,
  },
  {
    currency: "XCD",
    currencyName: "East Caribbean dollar",
    country: "Saint Vincent and the Grenadines",
    isoAlpha2: "VC",
    isoNumeric3: 670,
  },
  {
    currency: "WST",
    currencyName: "Samoan tala",
    country: "Samoa",
    isoAlpha2: "WS",
    isoNumeric3: 882,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "San Marino",
    isoAlpha2: "SM",
    isoNumeric3: 674,
  },
  {
    currency: "STD",
    currencyName: "São Tomé and Príncipe dobra",
    country: "São Tomé and Príncipe",
    isoAlpha2: "ST",
    isoNumeric3: 678,
  },
  {
    currency: "SAR",
    currencyName: "Saudi riyal",
    country: "Saudi Arabia",
    isoAlpha2: "SA",
    isoNumeric3: 682,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Senegal",
    isoAlpha2: "SN",
    isoNumeric3: 686,
  },
  {
    currency: "RSD",
    currencyName: "Serbian dinar",
    country: "Serbia",
    isoAlpha2: "RS",
    isoNumeric3: 688,
  },
  {
    currency: "SCR",
    currencyName: "Seychellois rupee",
    country: "Seychelles",
    isoAlpha2: "SC",
    isoNumeric3: 690,
  },
  {
    currency: "SLL",
    currencyName: "Sierra Leonean leone",
    country: "Sierra Leone",
    isoAlpha2: "SL",
    isoNumeric3: 694,
  },
  {
    currency: "SGD",
    currencyName: "Singapore dollar",
    country: "Singapore",
    isoAlpha2: "SG",
    isoNumeric3: 702,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Slovakia",
    isoAlpha2: "SK",
    isoNumeric3: 703,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Slovenia",
    isoAlpha2: "SI",
    isoNumeric3: 705,
  },
  {
    currency: "SBD",
    currencyName: "Solomon Islands dollar",
    country: "Solomon Islands",
    isoAlpha2: "SB",
    isoNumeric3: "090",
  },
  {
    currency: "SOS",
    currencyName: "Somali shilling",
    country: "Somalia",
    isoAlpha2: "SO",
    isoNumeric3: 706,
  },
  {
    currency: "ZAR",
    currencyName: "South African rand",
    country: "South Africa",
    isoAlpha2: "ZA",
    isoNumeric3: 710,
  },
  {
    currency: "KRW",
    currencyName: "South Korean won",
    country: "South Korea",
    isoAlpha2: "ZA",
    isoNumeric3: 410,
  },
  {
    currency: "EUR",
    currencyName: "Euro",
    country: "Spain",
    isoAlpha2: "ES",
    isoNumeric3: 724,
  },
  {
    currency: "LKR",
    currencyName: "Sri Lankan rupee",
    country: "Sri Lanka",
    isoAlpha2: "LK",
    isoNumeric3: 144,
  },
  {
    currency: "SDG",
    currencyName: "Sudanese pound",
    country: "Sudan",
    isoAlpha2: "SD",
    isoNumeric3: 729,
  },
  {
    currency: "SRD",
    currencyName: "Surinamese dollar",
    country: "Suriname",
    isoAlpha2: "SR",
    isoNumeric3: 740,
  },
  {
    currency: "SEK",
    currencyName: "Swedish krona",
    country: "Sweden",
    isoAlpha2: "SE",
    isoNumeric3: 752,
  },
  {
    currency: "CHF",
    currencyName: "Swiss franc",
    country: "Switzerland",
    isoAlpha2: "CH",
    isoNumeric3: 756,
  },
  {
    currency: "SYP",
    currencyName: "Syrian pound",
    country: "Syria",
    isoAlpha2: "SY",
    isoNumeric3: 760,
  },
  {
    currency: "TWD",
    currencyName: "New Taiwan dollar",
    country: "Taiwan",
    isoAlpha2: "TW",
    isoNumeric3: 158,
  },
  {
    currency: "TJS",
    currencyName: "Tajikistani somoni",
    country: "Tajikistan",
    isoAlpha2: "TJ",
    isoNumeric3: 762,
  },
  {
    currency: "TZS",
    currencyName: "Tanzanian shilling",
    country: "Tanzania",
    isoAlpha2: "TZ",
    isoNumeric3: 834,
  },
  {
    currency: "THB",
    currencyName: "Thai baht",
    country: "Thailand",
    isoAlpha2: "TH",
    isoNumeric3: 764,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "Timor-Leste",
    isoAlpha2: "TH",
    isoNumeric3: 626,
  },
  {
    currency: "XOF",
    currencyName: "West African CFA franc",
    country: "Togo",
    isoAlpha2: "TG",
    isoNumeric3: 768,
  },
  {
    currency: "TOP",
    currencyName: "Tongan pa'anga",
    country: "Tonga",
    isoAlpha2: "TO",
    isoNumeric3: 776,
  },
  {
    currency: "TTD",
    currencyName: "Trinidad and Tobago dollar",
    country: "Trinidad and Tobago",
    isoAlpha2: "TT",
    isoNumeric3: 780,
  },
  {
    currency: "TND",
    currencyName: "Tunisian dinar",
    country: "Tunisia",
    isoAlpha2: "TN",
    isoNumeric3: 788,
  },
  {
    currency: "TRY",
    currencyName: "Turkish lira",
    country: "Turkey",
    isoAlpha2: "TR",
    isoNumeric3: 792,
  },
  {
    currency: "TMT",
    currencyName: "Turkmenistan manat",
    country: "Turkmenistan",
    isoAlpha2: "TM",
    isoNumeric3: 795,
  },
  {
    currency: "AUD",
    currencyName: "Australian dollar",
    country: "Tuvalu",
    isoAlpha2: "TV",
    isoNumeric3: 798,
  },
  {
    currency: "UGX",
    currencyName: "Ugandan shilling",
    country: "Uganda",
    isoAlpha2: "UG",
    isoNumeric3: 800,
  },
  {
    currency: "UAH",
    currencyName: "Ukrainian hryvnia",
    country: "Ukraine",
    isoAlpha2: "UA",
    isoNumeric3: 804,
  },
  {
    currency: "AED",
    currencyName: "United Arab Emirates dirham",
    country: "United Arab Emirates",
    isoAlpha2: "AE",
    isoNumeric3: 784,
  },
  {
    currency: "GBP",
    currencyName: "British pound",
    country: "United Kingdom",
    isoAlpha2: "GB",
    isoNumeric3: 826,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "United States",
    isoAlpha2: "US",
    isoNumeric3: 840,
  },
  {
    currency: "UYU",
    currencyName: "Uruguayan peso",
    country: "Uruguay",
    isoAlpha2: "UY",
    isoNumeric3: 858,
  },
  {
    currency: "UZS",
    currencyName: "Uzbekistani som",
    country: "Uzbekistan",
    isoAlpha2: "UZ",
    isoNumeric3: 860,
  },
  {
    currency: "VUV",
    currencyName: "Vanuatu vatu",
    country: "Vanuatu",
    isoAlpha2: "VU",
    isoNumeric3: 548,
  },
  {
    currency: "VEF",
    currencyName: "Venezuelan bolívar",
    country: "Venezuela",
    isoAlpha2: "VE",
    isoNumeric3: 862,
  },
  {
    currency: "VND",
    currencyName: "Vietnamese dong",
    country: "Vietnam",
    isoAlpha2: "VN",
    isoNumeric3: 704,
  },
  {
    currency: "YER",
    currencyName: "Yemeni rial",
    country: "Yemen",
    isoAlpha2: "YE",
    isoNumeric3: 887,
  },
  {
    currency: "ZMW",
    currencyName: "Zambian kwacha",
    country: "Zambia",
    isoAlpha2: "ZM",
    isoNumeric3: 894,
  },
  {
    currency: "USD",
    currencyName: "United States dollar",
    country: "Zimbabwe",
    isoAlpha2: "ZW",
    isoNumeric3: 716,
  },
];

const baseMonths = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
const monthName = {
  1: "January",
  2: "February",
  3: "March",
  4: "April",
  5: "May",
  6: "June",
  7: "July",
  8: "August",
  9: "September",
  10: "October",
  11: "November",
  12: "December",
};

const monthAbbr = {
  1: "Jan.",
  2: "Feb.",
  3: "March",
  4: "April",
  5: "May",
  6: "June",
  7: "July",
  8: "Aug.",
  9: "Sept.",
  10: "Oct.",
  11: "Nov.",
  12: "Dec.",
};

const baseYears = [2020, 2021, 2022, 2023, 2024, 2025, 2026];

const sampleSize = Math.floor(Math.random() * 1000);
const sampleCountries = sampleWithReplacement(sampleSize, countries);
const sampleMonths = sampleWithReplacement(sampleSize, baseMonths);
const sampleYears = sampleWithReplacement(sampleSize, baseYears);
const sampleDates = sampleYears.map((year, i) => {
  let month = sampleMonths[i];
  let modyear = year;
  if (year === 2020 && month <= 8) {
    modyear = sampleWithReplacement(1, baseYears.slice(1))[0];
  }
  return new Date(modyear, month);
});

export {
  topicOptions,
  countries,
  sampleCountries,
  sampleDates,
  baseMonths,
  monthName,
  monthAbbr,
};
